#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

# Run db:migrate
#pushd ${OPENSHIFT_REPO_DIR} > /dev/null
#bundle exec rake db:migrate RAILS_ENV="production"
#popd > /dev/null
echo "Stopping websocket server"
kill `ps -ef | grep websocket.rb | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
exit 0
